### ISSUE TITLE
Shouldn't pygame's version be 2.0.0?

### ISSUE THREAD

**Issue by DH-O** [hhhusiyi-monash/UPDeT#11]
When I install below
`pip install -r requirements.text`

smac 1.0.0 has requirement pygame>=2.0.0, but you'll have pygame 1.9.4 which is incompatible.
is poped up

**Comment by Theohhhu** [comment]
Just replace the proper package if bugs are reported. The **requirements.text** file is as same as the original Pymarl Repository.
