### ISSUE TITLE
Unsatisfactory experimental results

### ISSUE THREAD

**Issue by zichuan-liu** [hhhusiyi-monash/UPDeT#14]
Hi, i wanna know why I run 5m_vs_6m win rate is only about 20%-40% in qmix, the same happens on 'rnn' and 'updet', I also use sc2 version 4.10, run 2M steps, torch=1.4.1, the code did not make any changes. 
Is there anyone else like this? How do I reproduce these results, if you can answer too thanks!

**Comment by zichuan-liu** [comment]
I solved it

**Comment by CrazySssst** [comment]
Hi, I have the same problem (QMIX 5m_vs_6m sc2 version 4.10, run 2M, perform very low). Can you tell me how to solve it?
