### ISSUE TITLE
question about 7m-5m-3m transfer learning

### ISSUE THREAD

**Issue by ohoneyd** [hhhusiyi-monash/UPDeT#4]
for 7m-5m-3m transfer learning，when I use the updet model combined with qmix，there is a dimension mismatch problem. 
Only the updet model combined with VDN support  transfer learning?

**Comment by hhhusiyi-monash** [comment]
Try to only load the agent, not the mixer. The transfer learning pipeline can still work. 
And notice it may take some time for mixers like QMIX and QTRAN to train from scratch even with a good agent.

**Comment by ohoneyd** [comment]
> Try to only load the agent, not the mixer. The transfer learning pipeline can still work.
> And notice it may take some time for mixers like QMIX and QTRAN to train from scratch even with a good agent.

Thanks! And is Figure 5 the result for VDN mixer?

**Comment by hhhusiyi-monash** [comment]
Yes.
