### ISSUE TITLE
我想在coma上 使用这个updet可以吗 I want to use this updet on coma, is it okay?

### ISSUE THREAD

**Issue by yyds-xtt** [hhhusiyi-monash/UPDeT#9]

**Comment by yyds-xtt** [comment]
我想在coma上 使用这个updet可以吗
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by yyds-xtt** [comment]
I want to use this updet on coma, is it okay?

**Comment by Theohhhu** [comment]
Sorry I haven't tested UPDeT on COMA.  But you could give it a shot.
